/**
 * Tests for BepInEx config module
 */

import { describe, expect, it } from "vitest";
import {
  type BepInExFrameworkConfig,
  DEFAULT_BEPINEX_FRAMEWORK_CONFIG,
  parseBepInExFrameworkConfig,
} from "./config.js";

describe("parseBepInExFrameworkConfig", () => {
  it("should return default config for empty content", () => {
    const result = parseBepInExFrameworkConfig("");
    expect(result).toEqual(DEFAULT_BEPINEX_FRAMEWORK_CONFIG);
  });

  it("should parse console enabled setting", () => {
    const content = `
[Logging.Console]
Enabled = true
`;
    const result = parseBepInExFrameworkConfig(content);
    expect(result.consoleEnabled).toBe(true);
  });

  it("should parse console disabled setting", () => {
    const content = `
[Logging.Console]
Enabled = false
`;
    const result = parseBepInExFrameworkConfig(content);
    expect(result.consoleEnabled).toBe(false);
  });

  it("should parse disk logging setting", () => {
    const content = `
[Logging.Disk]
Enabled = true
`;
    const result = parseBepInExFrameworkConfig(content);
    expect(result.diskLoggingEnabled).toBe(true);
  });

  it("should parse unity logging setting", () => {
    const content = `
[Logging.Unity]
Enabled = false
`;
    const result = parseBepInExFrameworkConfig(content);
    expect(result.unityLogEnabled).toBe(false);
  });

  it("should parse multiple sections", () => {
    const content = `
[Logging.Console]
Enabled = false

[Logging.Disk]
Enabled = true

[Logging.Unity]
Enabled = true
`;
    const result = parseBepInExFrameworkConfig(content);
    expect(result).toEqual({
      consoleEnabled: false,
      diskLoggingEnabled: true,
      unityLogEnabled: true,
    } satisfies BepInExFrameworkConfig);
  });

  it("should ignore comments and empty lines", () => {
    const content = `
# This is a comment
; This is also a comment

[Logging.Console]
# Console setting
Enabled = false
`;
    const result = parseBepInExFrameworkConfig(content);
    expect(result.consoleEnabled).toBe(false);
  });

  it("should handle full BepInEx.cfg content", () => {
    const content = `## Settings file was auto-generated by BepInEx

[Caching]
EnableAssemblyCache = true

[Chainloader]
HideManagerGUI = false

[Logging.Console]
Enabled = false
PreventClose = false

[Logging.Disk]
Enabled = true
AppendLog = false

[Logging.Unity]
Enabled = true
`;
    const result = parseBepInExFrameworkConfig(content);
    expect(result).toEqual({
      consoleEnabled: false,
      diskLoggingEnabled: true,
      unityLogEnabled: true,
    } satisfies BepInExFrameworkConfig);
  });

  it("should be case insensitive for section names", () => {
    const content = `
[LOGGING.CONSOLE]
enabled = FALSE
`;
    const result = parseBepInExFrameworkConfig(content);
    expect(result.consoleEnabled).toBe(false);
  });

  it("should handle whitespace around values", () => {
    const content = `
[Logging.Console]
Enabled  =   true
`;
    const result = parseBepInExFrameworkConfig(content);
    expect(result.consoleEnabled).toBe(true);
  });
});

describe("DEFAULT_BEPINEX_FRAMEWORK_CONFIG", () => {
  it("should have console enabled by default", () => {
    expect(DEFAULT_BEPINEX_FRAMEWORK_CONFIG.consoleEnabled).toBe(true);
  });

  it("should have disk logging enabled by default", () => {
    expect(DEFAULT_BEPINEX_FRAMEWORK_CONFIG.diskLoggingEnabled).toBe(true);
  });

  it("should have unity logging enabled by default", () => {
    expect(DEFAULT_BEPINEX_FRAMEWORK_CONFIG.unityLogEnabled).toBe(true);
  });
});
