/**
 * BepInEx.rcon plugin configuration reader/writer
 * Syncs the app's RCON settings with the BepInEx.rcon plugin config file
 * (BepInEx/config/nl.avii.plugins.rcon.cfg)
 *
 * The plugin config is the source of truth for what port/password the RCON
 * server is actually listening on.
 */

import fs from "node:fs/promises";
import path from "node:path";
import { createLogger } from "../utils/logger.js";
import { getConfigPath } from "./paths.js";

const log = createLogger("bepinex-rcon-config");

/** BepInEx.rcon config filename */
export const RCON_CONFIG_FILE = "nl.avii.plugins.rcon.cfg";

/** Default RCON port used by BepInEx.rcon (game port + 2) */
export const BEPINEX_RCON_DEFAULT_PORT = 2458;

/** Default RCON password used by BepInEx.rcon */
export const BEPINEX_RCON_DEFAULT_PASSWORD = "ChangeMe";

/** Parsed RCON plugin configuration */
export type RconPluginConfig = {
  enabled: boolean;
  port: number;
  password: string;
};

/**
 * Reads and parses the BepInEx.rcon plugin configuration file.
 * Returns null if the file does not exist yet (plugin hasn't run once).
 *
 * @param valheimPath Optional override for the Valheim server directory
 * @returns Parsed config or null if missing
 */
export async function readRconPluginConfig(
  valheimPath?: string
): Promise<RconPluginConfig | null> {
  const cfgPath = path.join(getConfigPath(valheimPath), RCON_CONFIG_FILE);

  let content: string;
  try {
    content = await fs.readFile(cfgPath, "utf-8");
  } catch {
    log.debug("RCON plugin config not found (plugin may not have run yet)");
    return null;
  }

  return parseRconConfig(content);
}

/**
 * Writes the BepInEx.rcon plugin configuration file.
 * Creates the config directory if it doesn't exist.
 *
 * @param config The RCON settings to write
 * @param valheimPath Optional override for the Valheim server directory
 */
export async function writeRconPluginConfig(
  config: RconPluginConfig,
  valheimPath?: string
): Promise<void> {
  const configDir = getConfigPath(valheimPath);
  await fs.mkdir(configDir, { recursive: true });

  const cfgPath = path.join(configDir, RCON_CONFIG_FILE);
  const content = serializeRconConfig(config);

  await fs.writeFile(cfgPath, content, "utf-8");
  log.info("Wrote RCON plugin config", { port: config.port });
}

/**
 * Checks whether the BepInEx.rcon plugin config file exists.
 *
 * @param valheimPath Optional override for the Valheim server directory
 * @returns True if the config file is on disk
 */
export async function rconPluginConfigExists(
  valheimPath?: string
): Promise<boolean> {
  const cfgPath = path.join(getConfigPath(valheimPath), RCON_CONFIG_FILE);
  try {
    await fs.access(cfgPath);
    return true;
  } catch {
    return false;
  }
}

// ── Internal helpers ──

/**
 * Parses BepInEx INI-style config content into structured config.
 *
 * The BepInEx.rcon plugin uses `Config.Bind("rcon", key, ...)` which
 * produces a `[rcon]` section. The parser is section-agnostic — it reads
 * all key=value pairs regardless of section header.
 *
 * Format example:
 * ```ini
 * [rcon]
 * enabled = true
 * port = 2458
 * password = ChangeMe
 * ```
 */
export function parseRconConfig(content: string): RconPluginConfig {
  const config: RconPluginConfig = {
    enabled: true,
    port: BEPINEX_RCON_DEFAULT_PORT,
    password: BEPINEX_RCON_DEFAULT_PASSWORD,
  };

  for (const rawLine of content.split("\n")) {
    const line = rawLine.trim();

    // Skip empty lines, comments, and section headers
    if (!line || line.startsWith("#") || line.startsWith("[")) continue;

    const eqIndex = line.indexOf("=");
    if (eqIndex === -1) continue;

    const key = line.slice(0, eqIndex).trim().toLowerCase();
    const value = line.slice(eqIndex + 1).trim();

    switch (key) {
      case "enabled":
        config.enabled = value.toLowerCase() === "true";
        break;
      case "port": {
        const parsed = Number.parseInt(value, 10);
        if (!Number.isNaN(parsed) && parsed >= 1024 && parsed <= 65535) {
          config.port = parsed;
        }
        break;
      }
      case "password":
        config.password = value;
        break;
    }
  }

  return config;
}

/**
 * Serializes RCON plugin config to BepInEx INI format.
 *
 * The BepInEx.rcon plugin reads its settings from the `[rcon]` section
 * (defined by `Config.Bind("rcon", key, ...)`). Using any other section
 * name (e.g. `[General]`) causes BepInEx to ignore the values and fall
 * back to defaults — including `enabled = false`, which prevents the
 * RCON server from starting.
 */
export function serializeRconConfig(config: RconPluginConfig): string {
  return [
    "## Settings file was auto-generated by oz-dsm-valheim",
    "",
    "[rcon]",
    "",
    "## Enable RCON Communication",
    "# Setting type: Boolean",
    "# Default value: false",
    `enabled = ${config.enabled}`,
    "",
    "## Port to use for RCON Communication",
    "# Setting type: Int32",
    "# Default value: 2458",
    `port = ${config.port}`,
    "",
    "## Password to use for RCON Communication",
    "# Setting type: String",
    "# Default value: ChangeMe",
    `password = ${config.password}`,
    "",
  ].join("\n");
}
