/**
 * Valheim admin/ban/permitted list management
 * Handles reading and writing player lists
 */

import fs from "node:fs/promises";
import path from "node:path";

/** Types of player lists */
export type ListType = "admin" | "banned" | "permitted";

/** Mapping of list types to their file names */
const LIST_FILES: Record<ListType, string> = {
  admin: "adminlist.txt",
  banned: "bannedlist.txt",
  permitted: "permittedlist.txt",
};

/**
 * Ensure a file exists, creating it and parent directories if needed
 */
async function ensureFile(filePath: string): Promise<void> {
  try {
    await fs.access(filePath);
  } catch {
    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, "");
  }
}

/**
 * Gets the path to a list file, creating it if needed
 * @param type Type of list
 * @param savedir Valheim save directory
 * @returns Absolute path to the list file
 */
async function getListPath(type: ListType, savedir: string): Promise<string> {
  const listPath = path.join(savedir, LIST_FILES[type]);
  await ensureFile(listPath);
  return listPath;
}

/**
 * Reads a player list from disk
 * @param type Type of list to read
 * @param savedir Valheim save directory
 * @returns Array of Steam IDs from the list
 */
export async function readList(
  type: ListType,
  savedir: string
): Promise<string[]> {
  const listPath = await getListPath(type, savedir);
  const content = await fs.readFile(listPath, "utf-8");

  return content
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith("//"));
}

/**
 * Adds a Steam ID to a player list
 * @param type Type of list
 * @param steamId Steam ID to add
 * @param savedir Valheim save directory
 */
export async function addToList(
  type: ListType,
  steamId: string,
  savedir: string
): Promise<void> {
  const entries = await readList(type, savedir);

  if (!entries.includes(steamId)) {
    const listPath = await getListPath(type, savedir);
    await fs.writeFile(listPath, `${[...entries, steamId].join("\n")}\n`);
  }
}

/**
 * Removes a Steam ID from a player list
 * @param type Type of list
 * @param steamId Steam ID to remove
 * @param savedir Valheim save directory
 */
export async function removeFromList(
  type: ListType,
  steamId: string,
  savedir: string
): Promise<void> {
  const entries = await readList(type, savedir);
  const filtered = entries.filter((e) => e !== steamId);

  const listPath = await getListPath(type, savedir);
  await fs.writeFile(listPath, `${filtered.join("\n")}\n`);
}

/**
 * Clears all entries from a player list
 * @param type Type of list
 * @param savedir Valheim save directory
 */
export async function clearList(
  type: ListType,
  savedir: string
): Promise<void> {
  const listPath = await getListPath(type, savedir);
  await fs.writeFile(listPath, "// Auto-generated by OZ-Valheim DSM\n");
}

/**
 * Checks if a Steam ID is in a player list
 * @param type Type of list
 * @param steamId Steam ID to check
 * @param savedir Valheim save directory
 * @returns True if the ID is in the list
 */
export async function isInList(
  type: ListType,
  steamId: string,
  savedir: string
): Promise<boolean> {
  const entries = await readList(type, savedir);
  return entries.includes(steamId);
}

/**
 * Gets the count of entries in a player list
 * @param type Type of list
 * @param savedir Valheim save directory
 * @returns Number of entries in the list
 */
export async function getListCount(
  type: ListType,
  savedir: string
): Promise<number> {
  const entries = await readList(type, savedir);
  return entries.length;
}
